### ISSUE TITLE
modernizr not found

### ISSUE THREAD

**Issue by matthiasbeyer** [razor-x/jekyll-and-zurb#5]
Hi,

I tested this:

```
$ bundle && bower install && bundle exec jekyll s
```

On master, 2.11.4 and 2.11.3 - it always resulted in:

```
Configuration file: /tmp/jekyll-and-zurb/_config.yml
            Source: /tmp/jekyll-and-zurb
       Destination: /tmp/jekyll-and-zurb/_site
      Generating... 
  Liquid Exception: couldn't find file 'modernizr/modernizr' (in /tmp/jekyll-and-zurb/_assets/javascripts/head.js.coffee.erb:2) in _layouts/default.html
jekyll 2.5.3 | Error:  couldn't find file 'modernizr/modernizr'
  (in /tmp/jekyll-and-zurb/_assets/javascripts/head.js.coffee.erb:2)

```

**Comment by razor-x** [comment]
I noticed this on a recent test build as well. Something might have changed with the modernizr repo or package. Looking into this now.

**Comment by matthiasbeyer** [comment]
Whoa this is so awesome! I hope you can fix this, I want to use your template for a template :grin:

**Comment by razor-x** [comment]
Looks like they released modernizr version 3.0 which is very different, but the Foundation bower package did not lock the major version at 2. I'm setting it as a main dependency with an explicit version. This is much more consistent anyway as I believe it was the only secondary dependency that was included and not version locked.

**Comment by razor-x** [comment]
Let me know if the new version get's it working. Enjoy :smiley:

**Comment by matthiasbeyer** [comment]
Thank you **so** much. Now I can start developing my template based on your template :smile:
