### ISSUE TITLE
Syntax highlighting seems to be broken

### ISSUE THREAD

**Issue by matthiasbeyer** [razor-x/jekyll-and-zurb#6]
Tried with FF and chromium.

When generating a code block like so:

```
{% highlight ruby %}
def foo
  nil
end
{% endhighlight %}
```

Nothing gets highlighted - Do I have to enable it somehow?

**Comment by razor-x** [comment]
This uses highlightjs over the normal Jekyll Pygments based back end.

Simply use normal backtick github style markdown syntax (not the liquid tags) and it should work.

I believe you can still use the Pygments based highlighting but you need to enable it in `_config.yml`

**Comment by matthiasbeyer** [comment]
Sorry, but 

```
    ```ruby
    def foo
      nil
    end
    ```
```

results in the same. It just results (as the `hightlight` method does) in indented text (but wrong indention - the first line is indented twice, the second line once and the last line not) and another font and some block around the lines (around each line, not around all of them).

... Maybe I can add a screenshot...

**Comment by razor-x** [comment]
Ok, I just tested this on a fresh clone and created a single post with `.md` extension with the content

    ---
    layout: post
    ---
    
    ```ruby
    def foo
      nil
    end
    ```

I should have given you a working example yesterday, but I was in a bit of a rush at the time.

Perhaps you did not apply the post or default layout to your page?

Also, you can choose your desired theme with this line: https://github.com/razor-x/jekyll-and-zurb/blob/ce74aaf4a71488e392cf6b43d67fbe8462b779bf/_assets/stylesheets/app.css.sass.erb#L2

**Comment by matthiasbeyer** [comment]
I did some modifications to the whole codebase, but I applied a layout for it.

The code is here:

* https://github.com/matthiasbeyer/wiki.template/tree/style-codeblocks

The relevant files are here:

* https://github.com/matthiasbeyer/wiki.template/blob/style-codeblocks/wiki/articles/The_Wiki.md
* https://github.com/matthiasbeyer/wiki.template/tree/style-codeblocks/_layouts

**Comment by razor-x** [comment]
In Chrome it renders correctly, but in Firefox I get the issue in your example image.  Perhaps a regression in highlightjs.

The really odd thing is I am using the latest version of this on two other sites where the code highlighting is working fine in both browsers. I'll see if I can work out what's going on.

**Comment by razor-x** [comment]
Ok, I think I worked it out. I removed fonts loaded via webfontloader in a previous commit. The empty array was generating an error. I think that error could stop some js execution, including highlightjs. I don't have the error on my other sites as they all load at least one font.

I am adding Roboto to the load list, as Foundation uses that font as a fallback anyway.

**Comment by matthiasbeyer** [comment]
So to fix the issue I can pull in your fixup commit, I guess?

**Comment by razor-x** [comment]
Yes, I'll also mark a new patch release. Add the line in the fonts file from this commit (https://github.com/razor-x/jekyll-and-zurb/commit/bef0c90069489e33c03948c73418748a1485b7d1) and let me know if it works for you.

**Comment by matthiasbeyer** [comment]
Works.
